import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import arrow from "@/public/arrow.svg";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Atribuição de Operador",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
      <Image alt="arrow" src={arrow}
        className="absolute -z-10 h-full sm:w-3/6 py-4 left-0 bottom-0"
      />
        {children}
      </body>
    </html>
  );
}
